spring.application.name=backend

# Importamos la conexión desde la carpeta "base de datos"
spring.config.import=file:../base de datos/conexion.properties

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
